### ISSUE TITLE
Meta issue for all problems around "Browse it"

### ISSUE THREAD

**Issue by MarcusDenker** [guillep/pharo-core#10773]
**Bug description**
Browse it needs some work 

We found that "Browse it" is supposed to mean "execute this, then browse the class of the result". Discussions have shown that this feature is used a lot and thus essential.

Accidentally, if you "browse it" of a global variable, it browses the class (it executes the code, browse the class of the result).
This has lead to people thinking of "browse it" as "browse the definition if it", because it does so for global references to classes.

Thus quite quickly, people think that when selecting a selector, "Browse it" should do what "implementors of" does and browse all the methods with that selector.

The problem is: the two features can not exist at the same time. "Browse it" can either be "evaluate this and an browse class" *or* it can be a non-evaluating "browse the definition of this". It can *not* be both, as it is not clear when it would evaluate and when not.

There are two more problems (not directly related): 

1. When not selecting anything, it automatically selects and that selection seems to be wrong in some cases.
2. When the selection is done manually and the selected text is not syntactically correct, the compiler complaints. But that is kind of expected, or not? "doIt" and "inspect it" do the same.

- [ ] Browse Class in code pane only works if entire class selected (senders/implementors correctly looks at AST) #9615
- [ ] evaluate: aString andDo: aBlock should better handle buggy expressions. #5013

This issue shows that a "browse Definitons of this" feature is missing.

 "implementors if" works like that to some extent, but it is too low level as it shows *methods* with a name, not class definitions or variable definitions.

already closed:

- [x] Browsing a Symbol produces an error / browse UndefinedObject #8889
- [x]  Browse does not bring the class #10733
- [x] Cmd+Browse raise a DNU #10695	
- [x] "Browse it" evaluates code. Can lead to bad side effects #8515
- [x] analyzeRead:by: sent to nil #9644
- [x] Another DNU when browsing class #9991

**Comment by MarcusDenker** [comment]
The code uses is different between NewTools and the browser (this is what #8889 mentions).

Both have problems, but the first step could be to make sure that they use the same code.
