### ISSUE TITLE
[Longterm Cleanup] fix or tag all "selectors send but not implemented"

### ISSUE THREAD

**Issue by MarcusDenker** [guillep/pharo-core#10834]
We should really have no uncontrolled sends of selectors in the system that are not implemented.

Normally can get all the problematic methods with: (but see below, there is a bug that breaks this for now)

```
SystemNavigation default allSentNotImplementedSelectors
```

Here is a todo:

- [ ] tag all false positive with the pragma ignoreNotImplementedSelectors:
- [ ] fix all the rest
- [ ] update release test #testNoSentNotImplementedSelectors

Here are existing issues that just list cases that need to be fixed:

- [ ] ccwArcSegment: sent but not implemented #6977
- [ ] Unimplemented message sent in EmbeddedFreeTypeFontInstaller>>#embedFilesInDirectory: #10632
- [x] RBEnvironmentVisitor seems like a dead code #14721
- [ ] https://github.com/pharo-project/pharo/issues/6976

Fixed:
- [x] allReferencesTo: aLiteral do: aBlock is called unknown messages #14400
- [x] our senders of non-existing selector #setSelectedIndex: #13531
- [x] https://github.com/pharo-project/pharo/issues/5849
- [x] ClyMethodTagsEditorMorph>>#build sends unimplemented method #9804
- [x] SpDialogWindowPresenter DNU #modalRelativeTo: #10831
- [x] SystemNavigation default allUnimplementedCalls size -> DNU #9777
- [x] add way to tag where we can not fix. DONE, there is #ignoreUnimplementedCalls:
- [x] https://github.com/pharo-spec/NewTools/issues/240
- [x] spotterLabel is undefined in spotterForSettingsFor: #10472
- [x] Broken FT2 library setting #10800
- [x] Unimplemented message send in FT2Face>>#emboldenOutline: #11634
- [x] 12110-ReAbstractCritique-asModalWindow  #12110

**Comment by MarcusDenker** [comment]
SystemNavigation new allUnimplementedCalls size   --> "338"

To see all the problematic methods, just inspect

```
SystemNavigation new allUnimplementedCalls 
```

**Comment by daniels220** [comment]
The release test you mention is actually `#testThatThereAreNoSelectorsRemainingThatAreSentButNotImplemented`—I want to mention it here so this issue appears in searches for that exact selector.

I wonder if, complementing the `ignoreNotImplementedSelectors:` pragma, it would be worth categorically excluding "test data"-type methods (e.g. all of `RBClassDataForRefactoringTest`), as these generally are either _not_ actually sent even though they may be referenced, or any resulting DNU is part of the intended behavior of the test (or will result in a failure, if it _is_ an accident). If this feels too open-ended, perhaps establish a rich set of canonical dummy selectors, or a canonical prefix for dummy selectors, that are allowed to be sent-but-not-implemented, as long as all sends are in `-Tests` packages.
