### ISSUE TITLE
[Meta] Tests to fix before we can enable Fluid Class Definitions

### ISSUE THREAD

**Issue by MarcusDenker** [guillep/pharo-core#11196]
#11194 has shown problems, we have to fix:

- [x] ChangeSetClassChangesTest>>testChangeClassCategory https://github.com/pharo-project/pharo/issues/11679
- [x] EpRevertTest>>testClassRemoval EpRevertTest>>testTraitRemoval https://github.com/pharo-project/pharo/issues/8179
- [x] RBRefactoringChangeTest>>testAddMetaclassPattern, RBRefactoringChangeTest>>testAddTraitPattern https://github.com/pharo-project/pharo/issues/11680

**Comment by MarcusDenker** [comment]
all done
