### ISSUE TITLE
Reduce #asSymbol sends to strings

### ISSUE THREAD

**Issue by MarcusDenker** [guillep/pharo-core#11330]
**Describe the problem**
When you check who executes String>>#asSymbol, there are many users that we can easily change to not need it.

This will of course not lead to any noticeable speedups, but it will make it much easier to analyse Symbol interning in the future (e.g. on code loading).

- [x]  reduce #asSymbol sends in Morph>>#adhereToEdge: #11329 
- [x] CompiledMethodTrailer>>#encode should hard-code the same cases as #decode.  https://github.com/pharo-project/pharo/pull/11350
- [ ] ThemeIcons>>#iconNamed:ifNone: runs very often in the fallback case (we can just rename the icon names) https://github.com/pharo-project/pharo/issues/11356
- [x] RBParser>>#parseKeywordMessageWith: creates not-needed symbols during parsing #11360

**Comment by MarcusDenker** [comment]
For the icons, we have now an issue, the rest is fixed --> I close this one
