### ISSUE TITLE
[Meta] Steps needed for ConstantBlocks

### ISSUE THREAD

**Issue by MarcusDenker** [guillep/pharo-core#11933]
This issue collects all TODOs to be done to be able to enable CleanBlocks by default. This is a subset of what needs to be fixed for CleanBlocks (see https://github.com/pharo-project/pharo/issues/11195 )

- [x] Announcements https://github.com/pharo-project/pharo/pull/12027
- [x]  two tests fail in StepIntoTest https://github.com/pharo-project/pharo/pull/12024
- [x] #testIsNotTerminatedWhenItIsInsideLastTerminationMethod fails https://github.com/pharo-project/pharo/pull/12026

```
testAccessingSubscribers – MacOSX64.Announcements.Core.Tests.Tests.AnnouncerTest
testHandleSubscriberClass – MacOSX64.Announcements.Core.Tests.Tests.AnnouncerTest
testSubscribersForClass – MacOSX64.Announcements.Core.Tests.Tests.AnnouncerTest
testAccessingSubscribers – MacOSX64.Announcements.Core.Tests.Tests.WeakAnnouncerTest
testHandleSubscriberClass – MacOSX64.Announcements.Core.Tests.Tests.WeakAnnouncerTest
testSubscribersForClass – MacOSX64.Announcements.Core.Tests.Tests.WeakAnnouncerTest

testStepIntoDeadContextShouldRaiseException – MacOSX64.Debugger.Model.Tests.Core.StepIntoTest
testStepIntoUntilTermination – MacOSX64.Debugger.Model.Tests.Core.StepIntoTest

testIsNotTerminatedWhenItIsInsideLastTerminationMethod – MacOSX64.Kernel.Tests.Extended.Processes.ProcessTest
```

**Comment by MarcusDenker** [comment]
For Announcers, I think we can just change the tests to use non-constant clean blocks for now.

We have to revisit the API for clean blocks, but using a constant block for an announcer is not something that makes sense (as the block would have no effect).
