### ISSUE TITLE
[Compiler][Meta] Steps to allow compiling of syntactically wrong code when loading code

### ISSUE THREAD

**Issue by MarcusDenker** [guillep/pharo-core#11944]
**Bug description**
When executing a DoIt with code that has syntax errors or if you load code (e.g a .cs), the compiler raises a SyntaxErrorNotification which then opens a SyntaxErrorDebugger.

- SyntaxErrorDebugger is broken and looks strange, it is hard to use, too
- Every error opens a new SyntaxErrorDebugger, making it in practice very time consuming and not scriptable
- The mechanism behind, the idea that an SyntaxErrorNotification can lead to the code being fixed in the exception raise code and then the compiler re-starting is very complex. See exception ReparseAfterSourceEditing 

**Idea**

- The Compiler already can compiled any text to some kind of AST (we use it for syntax higlighting).
- The Code Generator can generate code for the RBParseErrorNode (this for raises a RuntimeSyntaxError and open a normal Debugger )

We should make a list of questions to answer and things todo that would allow us to just load syntactically wrong code and compile a method for it.

This would then mean that all interaction about fixing syntax errors is delayed to after the code is loaded and uses normal tools. People could even use meta-programming (e.g. a RBParseErrorNode awary ParseTreeRewriter) to fix all the methods.

**TO CHECK**

- [ ] Git and syntactically wrong code: Can we just store it? Or do we add a #isFaulty check to forbid commits
- [x] #12918
- [x] Check the case that the error is in the method signature. 
- [x] Anything else?

Next step after:
- [ ] Enable it for DoIts and #evaluate:, as these do not create code that tools see, it should be save.

Fixed:

- [x] [Compiler] fix code generation when compiling syntax errors: EnglobingError #11947

**Comment by privat** [comment]
Some notes on error recovery. i.e. what happens when a faulty node is executed.

## Evaluate expression (DoIt method)

```st
Smalltalk compiler options: #( + #optionParseErrors); evaluate: '+1'.
```

* [x] launch a debugger with `RuntimeSyntaxError: Variable or expression expected`
* [x] sane stack trace (nil>>DoIt, OC>>evaluateDoIt, OC>>evaluate, OC>>evaluate:)
* [x] present original code
* [ ] correct code location. -> no visible cursor and error not located in the code
* [ ] reovery. no way to recover from here (cannot modify a doit method)

## Execute non installed method

```st
nil executeMethod: (Smalltalk compiler options: #( + #optionParseErrors ); compile: 'foo ^ +1')
```

* [x] launch a debugger with `RuntimeSyntaxError: Variable or expression expected`
* [x] sane stack trace (nil>>foo, nil>>executeMethod:)
* [ ] present original code. -> present decompiled code with `(RuntimeSyntaxError signalSyntaxError: '<an unprintable nonliteral value>')`
* [x] visible cursor and error located in the code (the signalSyntaxError: thing)
* [ ] recovery. no way to recover from here (can modify method but `key #foo not found in MethodDictionary` possibly a debugger bug #12931)

## Execute installed method

```st
nil class addSelector: #foo withMethod: (Smalltalk compiler options: #( + #optionParseErrors ); compile: 'foo ^ +1'). nil foo.
```

Note: it's weird that I needed `addSelector:withMethod:` and that there is no `install` on something in `CompiledMethod` or `OpalCompiler`.

* [x] launch a debugger with `RuntimeSyntaxError: Variable or expression expected`
* [x] sane stack trace (nil>>foo)
* [ ] present original code. -> present decompiled code with `(RuntimeSyntaxError signalSyntaxError: '<an unprintable nonliteral value>')`
* [x] visible cursor and error located in the code (the signalSyntaxError: thing)
* [x] can recover by removing the whole exception thing ang replacing it by a valid expression.

**Comment by privat** [comment]
Related issue: #13424

* [x] *Git and syntactically wrong code: Can we just store it?*
  Yes we can, for the same reason we can have bad merges in the .st files, or a script that just format your disk and kill your cat on installation.
  In fact, faulty code are currently handled much nicer than these issues: on commit there are critiques to warn you, and on load there are resumable CodeError, and if you proceed some RutimeError at execution. My only concern is possible file corruption if the format or the importer are fragile.
* [ ] *Enable it for DoIts and #evaluate:*
  For `evaluate:`, this is currently an opt-in option. I think this is ok to let the client control that. We can add a helper method `evaluateYolo:` or something :)
  For doit, you get currently a popup or a GUI feedback. Usually no debug window (and least on calypso or spec). Maybe it could make sense to be faulty and let runtime error be fired. Especially since undeclared variables are now failing at runtime. I will PR something
