### ISSUE TITLE
cleanup todo from #testClassSideInitializeMethodNeedsToBeInClassInitializationProtocol

### ISSUE THREAD

**Issue by MarcusDenker** [guillep/pharo-core#12444]
**Describe the problem**

```
	todo := #(#LGitDiffHunk).
```

this can removed after the following Steps are done:

- [x] libGit last version is in Pharo (PR is merged there)
- [x] Do PR to update test

DONE:
- [x] Updating Tonel version #12865
- [x] https://github.com/pillar-markup/Microdown/pull/644
- [x] https://github.com/pharo-vcs/libgit2-pharo-bindings/pull/72
- [x] https://github.com/pharo-vcs/tonel/pull/105
- [x] https://github.com/pharo-vcs/iceberg/pull/1669
