### ISSUE TITLE
[META][CI] TODO for a green CI

### ISSUE THREAD

**Issue by MarcusDenker** [guillep/pharo-core#12493]
**Bug description**
This Issue is a list of all the issues that we see on the CI.
test run aborted:
- [ ] #12502

Randomly failing tests:
- [ ] [CI] Linux: OSEnvironmentTest fail with "Illegal continuation byte for utf-8 encoding" #13070

Some tests do not clean up after they are run, related to e.g tools open this could lead to instability

- [ ] https://github.com/pharo-project/pharo/issues/12517

FIXED:
- [x] https://github.com/pharo-project/pharo/issues/12285
- [x] https://github.com/pharo-project/pharo/issues/12126 
- [x] [CI] Random failure: SpCodePresenterTest>>testDoBrowseSendersOfClassNameWhenInPlaygroundButNotAvailable #13108
- [x] [CI] FLCreateClassSerializationTest takes too much time #13142
- [x] https://github.com/pharo-project/pharo/issues/11407
- [x] https://github.com/pharo-project/pharo/issues/12478
- [x] [CI] Windows testrunner has problems #12763

**Comment by jecisc** [comment]
New one: https://github.com/pharo-project/pharo/issues/12783

**Comment by MarcusDenker** [comment]
As we just have two real problems left (win slave and the Subscript out of bounds), the meta issue is not needed anymore, I close it
