### ISSUE TITLE
[Meta-issue] improve faulty compiling

### ISSUE THREAD

**Issue by privat** [guillep/pharo-core#12883]
Parsing and compiling is an everyday job and is performed when you install a package, switch branch, compile a method or add a character in a method editor (because of highlighting).

AST-Code (and its client) and OpalCompiler have/had a limited approach when dealing with faulty code.

The historical approach was basically to fire the UI in case of code error, so the human can fix it (in a not-so interactive way).
This approach is somewhat limited if tools have to work during code edition (or on a random piece of code) to provide better user feedback.

Pharo included basic opt-in faulty parsing (and compiler related options) so AST clients can try to deal with faulty code (highlighting for instance). This Issue track improvement and discussions.

## Bad API

The main issue of the current API are:

* [ ] a lack of isolation with UI: magic requestor instance variable, compiler drives the UI presentation on syntax error or semantic error (with interactive menu)
  → mostly eliminated. Some requestor thing remains, but I wait for open season in spec/newtools repositories
* [x] a bloated code recovery: notification ping-pong (SyntaxErrorNotification, OCUndeclaredVariableWarning, ReparseAfterSourceEditing).
  → Now fixed
* [x] complex effects on the configuration: requestor and its interactiveness, optionParseErrors, optionParseErrorsNoInteractive. optionSkipSemanticWarnings
  → Now fixed
* [x] lack of robustness: fragile `errorblock` and `failBlock`, unclear exception signaler, unclear notification signaled and possibly resumed
  → Now fixed

## Current debugger GUI on faulty code

Some notes on error recovery. i.e. what happens when a faulty node is executed.

### Evaluate expression (DoIt method)

```st
Smalltalk compiler permitFaulty: true; evaluate: '1+¿'.
```

* [x] launch a debugger with `RuntimeSyntaxError: Unknown character`
* [x] sane stack trace (nil>>DoIt, OC>>evaluateDoIt, OC>>evaluate, OC>>evaluate:)
* [x] present original code
* [x] visible cursor and error located in the code
* [x] recovery. no way to recover from here, cannot modify a doit method, but it is a limitation of the debugger, not ours, so I add a checkmark

### Execute non installed method

```st
nil executeMethod: (Smalltalk compiler permitFaulty: true; compile: 'foo ^ 1+¿')
```

* [x] launch a debugger with `RuntimeSyntaxError: Unknown character`
* [x] sane stack trace (nil>>foo, nil>>executeMethod:)
* [x] present original code.
* [x] visible cursor and error located in the code
* [x] recovery. no way to recover from here. can modify method but `key #foo not found in MethodDictionary`  #12931. So a bug of the debugger, not ours, so I add a checkmark

### Execute installed method

```st
nil class compiler permitFaulty: true; install: 'foo ^ 1+¿'. nil foo.
```

* [x] launch a debugger with `RuntimeSyntaxError: Unknown character`
* [x] sane stack trace (nil>>foo)
* [x] present original code.
* [x] visible cursor and error located in the code
* [x] can recover by removing the `¿` replacing it by a valid expression, saving, and proceed

## Installing and committing faulty code

How far can faulty code goes?
Related issues and experiments: #11944 #13424

* [x] installing a faulty method. OK.
  Note this require direct call to `OpalCompiler` or other MOP facility.
  Editors won't let you install any faulty methods.
* [x] Creating a commit.
  Iceberg has no issue to commit the method.
  However, there is a #error critique `ReMethodHasSyntaxErrorRule`, so you cannot push faulty code unwillingly :)
  * [ ] Can faulty code mess with the serialization format (tonel or whatever) and corrupt the file?
    Note that file corruption should already be handled, as bad command-line file edition can happen.
    But I don't know is the serialization format is fragile if the method contains garbage.
    → I checked, It seems that yes, the format is very fragile. It uses an ad hoc scanner and expect the content to be well-formed. This is bad because 1. it is uselessly complex code 2. it forces it to be synchronized with the language features (e.g. new literals or something) 3. it's limiting.
    → Update: PR proposed: https://github.com/pharo-vcs/tonel/pull/108
* [x] Removing the faulty method (switch to a sane branch). Unloading the code was ok.
* [x] Checkout back the branch with the faulty method
  * [x] The diff is shown in the "preview", with the syntax error visible in the diff, but nothing is done to alert you.
    However, up to my knowledge, Iceberg never tries to warn you on the diff anyway. So full check mark here.
  * [x] Proceeding "checkout" works until it shows a `CodeError` debugger.
    Inspection of the syntax error is "manual" but easy (just inspect `self`). While it could be improved, it is much better than the awful syntax error debugger I removed at the beginning of Pharo12 (#12910). So full check mark here.
  * [x] Closing the debugger, cancel the checkout.
    Since there is nothing else in the commit, I don't know if the system is left in the middle or if there is some kind of transaction/rollback. However, this is a "classic" iceberg issue of fault handling and not specifically related to faulty code with syntax errors, so full check mark here
  * [x] Proceeding "checkout" again, bring the same debugger, Now I "proceed ▶️" (the button is green because CodeError are resumable) and the faulty method is installed. The idea is that you can fix it at your own pace.
* [x] Code change. Go to Epicea and try to "Revert..." the faulty method.
  Epicea show you the diff and ask you to confirm. All fine and it revert the bad method
* [x] Return to the code change. Try to "Apply..." the faulty method.
  Epicea show you the diff and ask you to confirm. ~~But a growl (popup infobox in the lower left corner of the screen) show you the description of the CodeError, instead of launching a debugger. Why? Why you failed me Epicea?~~
  fixed by #13425

I'm quite happy about the current status.

## List of things

* [x] Have a fully usable faulty AST tree with information
  * [ ] consistent and complete API to receive, query errors and warnings
    * #13029
    * #13037
    * #13057
    * #13087
    * #13174
    * #13243
    * #13344
    * #13350
    * #13384
  * [x] formatter
    * #12872
    * #12902
  * [ ] other cleaning
    * #13421 

* [ ] Work on RBScanner
  * [x] complete faulty scanning
    * #12857
    * #12892
    * #13135
  * [x] simplify API
    * #12835
    * #12900
  * [ ] update the documentation

* [ ] Work on RBParser
  * [x] complete faulty parsing
    * #12778
    * #12816
    * #12818
    * #12836
    * #12868
    * #12873
    * #12879
    * #12891
    * #13044
    * #13098
    * #13129
    * #13130
    * #13133
    * #13262
    * #13264
    * #13300
  * [ ] clean internal code & remove bugs
    * #11681
    * #12854 
    * #12861
    * #12874
    * #13398
  * [ ] better API
    * [x] faulty by default
    * [x] no more exception
    * #13042
    * #13080
  * [ ] update the documentation

* [ ] Errors and warnings
  * [ ] Clean the mess on exceptions
    * #12978
    * #12980
    * #13047
    * #13055
    * #13163
    * #13164
    * #13277
  * [ ] Better semantic
    * [ ] kill undefined warning
    * [x] kill unreachable error
    * [x] kill shadow error/warning
    * #12815
    * #13050
    * #13132
    * #13172
    * #13189
    * #13195
    * #13199
    * #13201
    * #13236
    * #13238
    * #13244
    * #13280 
    * #13286
    * #13297
    * #13422
    * #13470
    * #13471

* [ ] Work on OpalCompiler
  * [x] complete faulty semantic analysis
    * #12919
    * #13148
    * #13165
  * [ ] clean internal code
    * [x] Move code reparation (undeclared variable) far away
    * #13007
    * #13045
    * #13184
    * #13222
    * #13302
    * #13303
    * #13323
    * #13352
    * #13378
    * #13379
    * #13386
    * #13393
    * #13394
    * #13408
    * #13423
  * [ ] better API
    * [x] deprecate/unify optionParseErrors, optionSkipSemanticWarnings
    * [x] do not rely on interactiveness (except for "quirks mode")
    * [x] parse-only faulty by default
    * [x] compiler gain `install` #13152 
    * [x] unify error handling
    * [x] beef up `RBNotice`
    * [x] beef up `failBlock` with `RBNotice`
    * [x] kill most exception
    * [ ] move `requestor` for "quirks mode" only
    * [ ] cleanup `OpalCompiler` and `CompilationContext` state and responsibilities
    * [ ] opt-in faulty-compilation (image wide)
    * #13084
    * #13186
    * #13210
    * #13261
    * #13359

  * [ ] update the documentation

* [ ] User interface, editors & clients
  * [ ] UX improvements
    * [x] Show errors and warnings
    * [x] Kill the legacy syntax error window
    * [x] Have a rule for syntax error. There is already one! ReMethodHasSyntaxErrorRule
    * [ ] Get faulty methods in virtual protocol (calypso)
    * #12904 
    * #12910
    * #12934
    * #13073
    * #13450
    * https://github.com/pharo-spec/NewTools/pull/506
    * https://github.com/pharo-spec/NewTools/pull/508
  * [ ] Update other clients
    * #13162 
    * #13301
    * #13392
    * #13397
  * [ ] Clean the code & fix bugs
    * #12981
    * #12982
    * #13118
    * #13235
    * #13248
    * #13418

* [ ] Extra
  * [x] Test all the things
    * #12847
    * #12871
    * #12893
    * #12901
    * #12909
    * #12933
    * #12947
    * #12958
    * #12960
    * #12995
    * #13036
    * #13109
    * #13115
    * #13127
    * #13223
    * #13263

**Comment by jecisc** [comment]
New one :) 

https://github.com/pharo-project/pharo/issues/12886
