### ISSUE TITLE
[Meta Issue] Improve metamodel

### ISSUE THREAD

**Issue by jecisc** [guillep/pharo-core#13207]
I'll use this issue as a meta issue to list things I notice we can improve in the meta model.

- [ ] Protocol 
  - [ ] Protocol>>rename: should be deprecated since it does not announce the renaming. RPackage is using this method in the package renaming method
  - [ ] Update Calypso
    - [x] #14266
    - [x] #14247
    - [x] #14219
    - [x] #14188
    - [x] #14111
    - [x] #14069
  - [ ] MCTestCase: Rename "category" into "protocol"
  - [ ] RGBehavior>>#protocols should be renamed #protocolNames
  - [ ] Check why AbstractTool has #protocolSuggestionsFor: and is not using MethodClassifier
  - [ ] Check if EpProtocolAddition/EpProtocolRemoval should have a real protocol instead of a protocol name
  - [ ] MCWorkingCopy class>>#managersForClass:category:do: and related method should use "protocol" instead of category and maybe handle real protocols
  - [ ] MCWorkingCopy class >> classRemoved: would be cleaner if it used real protocols
  - [ ] EpMonitor>>#methodRemoved: could maybe use more real protocols for what it is doing
  - [ ] RPackageOrganizer>>#systemMethodRecategorizedActionFrom: could use real protocols to be simplified
  - [ ] Kill ClassOrganizationChunk
  - [ ] Use real protocols in MethodClassifier
  - [ ] ClyMethodDefinitionProperty could maybe use a real protocol?
  - [ ] RPackageOrganizer>>#packageForProtocol:inClass: should use a real protocol?
  - [ ] RPackageOrganizer>>#hasPackageForProtocol: should have a real protocol as parameter
  - [x] Remove the concept of "tags" to refer to protocols
    - [x] #14243
    - [x] #14078
    - [x] #14060
    - [x] #14049
    - [x] #13880 
    - [x] #13492
  - [ ] #13535
    - [ ] #13552
  - [x] #14273
  - [x] #14050
  - [x] #14047
  - [ ] #14264
  - [x] #13951 
  - [x] #13967
  - [x] #13936
  - [x] #13881
  - [x] #13730
  - [x] #13768
  - [x] #13494
  - [x] #13305
    - [x]  #13311
    - [x] #13331
    - [x] #13333
    - [x] #13369
  - [x]  #13749
  - [x] #13670
  - [x] #13669
  - [x] #13506
  - [x] #13444
  - [x] #13188
  - [x] #13173
  - [x] #13203
  - [x] #13190
  - [x] ClassOrganization
    - [x] #13861
      - [x] #13674
      - [x] #13843
      - [x] #13845
      - [x] #13842
      - [x] #13792
      - [x] #13776
      - [x] #13759
      - [x] #13753
      - [x] #13748
      - [x]  #13728
      - [x] #13692
      - [x] #13711
      - [x] #13658 
    - [x] Stabilize ClassOrganization API and behavior 
      - [x] #13659
      - [x] #13642
      - [x]  #13646
      - [x] #13644
      - [x] Make sure the API knows how to deal with real protocols
        - [x] #13373
          - [x] #13630
          - [x] #13621
          - [x] #13604 
        - [x] #13624 
        - [x] #13466
        - [x] #13454 
        - [x] #13443
        - [x] #13247
      - [x] #13653
        - [x] #13605
        - [x] #13582
        - [x] #13593
        - [x] #13457
        - [x] #13576
        - [x] #13533
        - [x] #13572
        - [x] #13539
      - [x] #13530
      - [x] #13480
      - [x] #13464
      - [x] #13458
      - [x] #13453
      - [x]  #13383
      - [x]  #13382
      - [x] #13356
      - [x] #13257
      - [x] #13334
      - [x] #13346
    - [x] #13702
    - [x] #13649
    - [x] #13381
    - [x] #13385
    - [x] #13358
    - [x] Remove AllProtocol
      - [x] #13256 
      - [x] #13275
      - [x] #13289
    - [x] #13187
      - [x] #13202
      - [x] #13234

- [ ] Packages
  - [ ] Clean tests
    - [ ] Add tests on package creation
    - [ ] Add tests on package removal
  - [ ] #14073
  - [x] Remove Monticello dependencies
    - [x] #14072
    - [x] #14036  
    - [x] #14065
    - [x] #14040 
    - [x] #14025
    - [x] #14019
  - [ ] Move from CategoryAnnouncement to PackageAnnouncement and PackageTagAnnouncement 
    - [x]  #14081
    - [x] #13970
  - [ ] Clean Package API
    - [ ] Unify package creation
      - [ ] #14113
      - [x] #14260
      - [x] #14254
    - [ ] RPackage should not add a way to remove a package without removing its content (#unregister)
    - [ ] #14283
    - [x] #14223
    - [x] Clean way to know if a package exists
      - [x] #14246
      - [x] #14232
      - [x] #14224
  - [ ] Kill global variable SystemOrganization
    - [ ] Deprecate SystemOrganization
    - [x] #13271
    - [x] #13306
  - [ ] Remove all references to `RPackageOrganizer default` to use `Smalltalk organization`
    - [x] #13666
    - [x] #13671
  - [ ] Remove the duplicated concept of "category" in RPackage
  - [ ] #classesInCategory: returns behavior and not classes. We should renamed it into #behaviorsInCategory: 
  - [ ] Add tests to SystemOrganizer (or to RPackageOrganizer that might succeed to it)
  - [ ] /!\ We should be able to create packages with the name of some package with tag (This one is important for multiple other issues
  - [ ] Improve Package and Tag mess
    - [ ] Fluid class definition #package: should not deal with tags
    - [ ] Tonel should export #package: and #tag:  
    - [ ] Tonel should use #package: and #tag: when present instead of #category: while loading code
  - [ ] Remove the “R” from package MM names
  - [ ] Packaging system should not reference SystemAnnouncer everywhere but hold an instance of the announcer. The default organizer would use the system wise one while other instances could use their own announcer. Like this, we can update the tests to be sure they do not pollute the image with tests related announcements
  - [ ] RPackageOrganizer "packageNames" should not be sorted
  - [ ] RPackageOrganizer>>#basicInitializeFromPackagesList: is too Monticello specific
  - [ ] ClassDescription>>#notifyRepackage:method:oldProtocol:newProtocol: should not try to decouple RPackage
  - [ ] Rename announcement dealing methods of RPackageOrganizer to follow usual conventions 
  - [ ] Add superclass to RPackageSet and RPackage to factories some code
  - [ ] Remove RPackage>>organizer
  - [ ] Deprecate RPackageOrganizer>>default
  - [ ] Deprecate `Smalltalk organization`
  - [ ] Remove newName inst var of Package and Package tag announcements
  - [ ] Add tests on package file out
  - [ ] Add tests on announcements
  - [ ] Creating a class adds two times the class to the package (#addClassDefinition: is called twice)
  - [ ] Remove references to PackageInfo that are still there (I just found one in Gofer and I removed one in the bootstrap code)
  - [x] #14119
  - [ ] #14086
  - [x] #14272
  - [ ] #14281
  - [x] #14026
  - [x]  #13970
  - [x] #13509
  - [x] #13503
  - [x] #13401
  - [x] #13919
  - [x] #13854
  - [x] #13660
  - [x] #13496
  - [x] #13505
  - [x] #13206
  - [x] Kill SystemOrganizer
    - [x] #13690
    - [x] #13677
    - [x] #13245
    - [x] #13258
    - [x] #13259 
      - [x] #13314
    - [x]  #13403

- Class
  - [x] #13551

- CompileMethod
  - [ ] split CompilerMethod into two, a normal class Method that takes care of metamodel things (and have ivars!) and a CompilerMethod for runtime details (special class with constraints) that can more independent of the metamodel organization :)

- Kernel code readability
  - [x] #13197 
  - [x] #13200
  - [ ] Rename "sel" variables into "selector" and "sels" into "selectors"

- Traits
  - [ ] Rework the Trait hierarchy. Ideally we should have TraitDescription inheriting from Behavior

- Deprecations improvements 
  - [ ] Automatic class renaming
  - [ ] Make tonel export deprecated class names
  - [ ] Enable to define deprecated class names through FluidClassBuilder (requires previous step)
  - [x]  #13618
  - [x] #13348

- Other
  - [ ] MethodAddition should not write the source itself but compile like a classic method.
  - [ ] #13137
  - [ ] Check why Iceberg has dirty packages while discarding changes show no changes
  - [ ] Make bootstrap use GlobalVariable instead of association
  - [x] #13789
  - [ ] ShiftClassInstaller should not use #isVariable but delegate to the layout the things
  - [x] CompiledMethod>>basicNew(:) should be pushed up on CompiledCode
  - [ ] Check it #instSpec is in synch with the LayoutHierarchy

There are still way more to do and I'll update this list little by little

**Comment by privat** [comment]
* [ ] split `CompilerMethod` into two, a normal class `Method` that takes care of metamodel things (and have ivars!) and a `CompilerMethod` for runtime details (special class with constraints) that can more independent of the metamodel organization :)

**Comment by jecisc** [comment]
That is a big step :O 
But I can see the interest

**Comment by privat** [comment]
It is, and won't be easy

**Comment by jecisc** [comment]
Almost everything I wanted to do is done and I'll not have much time to work more on this so I'm closing.
