### ISSUE TITLE
[Meta issue] detaching AST and CompilationContext?

### ISSUE THREAD

**Issue by privat** [guillep/pharo-core#13508]
AST, and especially the root node `RBMethodNode` have a lot of responsibilities. As a grammatical representation of the source code, obviously, but also to manage its own compilation.

**Update:** checked boxes are resolved

Currently, some compilation concerns are not clearly assigned between `RBMethodNode` and `OpalCompiler`
Methods of `RBMethodNode` with the main compilation (or related) responsibility (simple wrappers excluded) are:

* [ ] bcToASTCache
* [x] compiledMethod #13514
* [x] doSemanticAnalysis #13517
* [ ] generate:
* [ ] generateIR
* [ ] generateMethod
* [x] method #13514
* [ ] scope

This means that the ASTs have to store a lot of data through the god-data-class CompilationContext (that includes potentially GUI windows). Beside storing, this data is exposed and used by the following methods that rely on the existence of a compilation context in a method node:

* [ ] `CDClassNameNode>>#existingBindingIfAbsent:` to get the environment of the scope of the node (why?)
* [x] `CompiledMethod>>#parseTree` to store the compiled method in the context (who use that?) #13514
* [x] `OCASTSemanticAnalyzer>>#visitPragmaNode:` to set compilerOptions: given with pragma  #13511
* [x] `OCASTTranslator>>#translateFullBlock:` to initialize the compilationContext of the methodBuilder ivar (maybe the ivar should be in the translator)  #13511
* [x] `OCASTTranslator>>#visitMethodNode:` same  #13511
* [x] `RFASTTranslator>>#visitMethodNode:` same  #13511
* [ ] all `RBMessageNode>>#isInline...` to check the `optionInline...` flag of the compilationContext and decide if the expression should be inlined
* [x] `RBProgramNode>>#asDoItForContext:` only one client #13520
* [x] `RBMethodNode>>#method` because the compiled method might be stored in the compilation context #13514
* [ ] `RBMethodNode>>#methodClass` this one is surprising, a method node does not know its own class but need a full context and scope
* [ ] `RBMethodNode>>#methodClass:` this one updates or creates a compilationContext. Some clients might not expect this side effect
* [ ] `RBMethodNode>>#semanticScope:` this one also update or create a compilationContext
* [x] `RBValueNode>>#evaluateForContext:` only used in a single test #13520
* [x] `RBValueNode>>#evaluateForReceiver:` #13520
* [x] `RBVariableNode>>#completionEntries:` to get the class  #13511
* [ ] `ReflectiveMethod>>#generatePrimitiveWrapper` to configure special semantic analyzer and translator classes in the compiled context of the node

As an additional complexity, some of these methods fallback to their own custom defaults if for some reason the method node has no associated compilation context.

## Related high level questions

* Does it make sense to have a whole compilationContext ivar on `RBMethodNode`? What specific piece of data are really needed?
* Who has the responsibility to decide how a method is compiled? Including special parsing/analysis/transforming classes, plugins, scope, etc.
* What should be the role of `OpalCompiler`? a simple facade? an orchestrator of compilation pipelines?
* What is policy, and what is mechanism? Low level entities usually have the responsibility to perform the operations and high level entities (and builders/transformers) have the responsibility to decide what to do and why.
* What is the expected role of AST? Transient and throwable data to manipulate source code? Something more persistent? Something more coupled with the live environment (imagine that updating some AST automatically updates the installed method)...

## The plan

* [ ] Replace use of `RBMethodNode>>#compilationContext` if something better is available
* [ ] Use semantic analysis to decorate nodes with semantic information (removing the reliance on the compilation context to retrieve this information)
* [ ] Decide what to do with `isInline` that is problematic and even used in some rules (I don't think rules should be dependent on compilation options, but that's another issue)
* [ ] Detach compilationContext from `IRMethod`
* [ ] Move back compilation services to OpalCompiler but try to keep a compatible API in RBMethodNode.
* [ ] Merge CompilationContext and OpalCompiler

**Comment by privat** [comment]
I also looked what is the usage of compilationContext in IR related classes.

The thing is that most classes are nested (and pass around the compilation context), therefore if the final instances of the chain legitimately need it, then all other previous instance must have it.
This also includes data-oriented classes (classes that represent final or intermediate results, like IRMethod) because they are responsible for their own transformations.

But what are these legitimate uses?

* compilation options, that might trigger different code path
* dependency injection. Class names (globals) are not used directly, but asked to the compilation context. This includes many kinds of classes, including `CompiledMethod` that is not known by IRBytecodeGenerator (a very deep and late class in the compilation chain). See `IRBytecodeGenerator>>#compiledMethodWith:header:literals:`

Some unused options one might be removed, but otherwise, having options is good, and having the ability to configure them at the `OpalCompiler` level is also good.

Dependency injection can also be a good design pattern. If is not clear however if all the numerous dependency injection points are really used for something (in production, or in tests to inject mock classes for instance) or if they just add complexity without any real gain.

Anyway, can we remove the dependency on the god-data-class CompilationContext? There might be various approaches (and combination of approaches):
* Move options and dependency injection into a smaller class (without scope, requestor nor AST plugins)
* Redesign the responsibilities to reduce the depth of the call chains. But it could mean that the data-oriented classes will no more be responsible for their own transformation, but a higher-up entity that know the policy and options. This is not clear what it entails exactly, nor if the redesign will be that much better.
* Pass around the context as method argument without storing it in the instance. It is not clear if this approach is really usable here.

**Comment by jecisc** [comment]
Just reading what you are writing, I like the idea of splitting the responsibilities of the god class.

But this is purely based on what you wrote since I don’t know really well this part of the system
