### ISSUE TITLE
[Meta] Simplify CompiledMethod trailer: just support fixed sourcePointers

### ISSUE THREAD

**Issue by MarcusDenker** [guillep/pharo-core#13512]
**Bug description**

CompiledMethodTrailer is quite complex for what it does. In the end, the compiledMethod stores a sourcePointer in the 4 last bytes. We need 1 bit to destinguish sources from .changes, so the 32bits should be good for an offset in 2GB .changes and .sources

But the encoding used is quite strange, for one, we use the last byte to define which encoding we use. This is needed as with 3 bytes, we can not encode the sourcePointer already for our ~40MB .sources, so we use a #VarLengthSourcePointer for those:

```
Smalltalk globals methods count: [ :method | method trailer kind == #VarLengthSourcePointer ].
 "19841"
```

Variable length sourcePointers are not that nice in general, as we have to create another compiledMethod (and do a become) if we want to set it.

TODO

Remove the need for embedding sources in the trailer
- [x] CompiledMethod simplification: remove the last user of #copyWithSource: #13507
- [x] remove all unsused encodings from CompiledMethodTrailer. #13510
- [x] check users of generateWithSource: removed by https://github.com/pharo-project/pharo/pull/13514
- [x] fix Fuel to not use source embedding (see FLCompiledMethodCluster class>>#setTrailerWithSourceCode) #13522
- [x] CompiledMethodTrailer: remove #EmbeddedSource and #EmbeddedSourceWide encoding #13522
- [x] CompiledMethodTrailer: just use #asByteArrayOfSize: 4 to encode sourcePointer #13527
- [x] Cleanup CompiledMethodTrailer extendedSourcePointer #13545
- [x] simplify CompiledMethod>>#setSourcePointer: #13546
- [x] simplify CompiledMethod>>#endPC, we do not need to instantiate CompiledMethodTrailer anymore #13546
- [x] Cleanup: CompiledMethodTrailer should not create methods #13555
- [x] Cleanup: Fuel does not need to use #copyWithTrailerBytes: #13560
- [x] do not use CompiledMethodTrailer in ReflectiveMethod>>#compileAST #13564
- [x] Compiler: Cleanup for trailer removal in IRByteCodeGenerator #13565
- [x] remove CompiledMethodTrailer usage in the compiler (not used by the bytecode generator anymore) #13575
- [x] Deprecate class CompiledMethodTrailer  #13579
- [x] introduce CompiledMethod>>#clearSourcePointer and #sourcePointer: #13578
- [x] simpler sourcePointer encoding #13583
- [x] Fix-SourceFileArrayTest for new encoding #13596

**Comment by MarcusDenker** [comment]
For using 5 bytes, I added a new issue: https://github.com/pharo-project/pharo/issues/13616
