### ISSUE TITLE
Compiler: improve ReservedVariables

### ISSUE THREAD

**Issue by MarcusDenker** [guillep/pharo-core#13675]
**Describe the problem**
The ReservedVariables (ala PseudoVariables) are singletons and are created via methods likes #thisContextNode.

Why is this a problem? For one, they are too special, all other variables are just looked up in the scope by name, which is perfectly possible for ReservedVariables, too, as SystemDictionary knows them. 

The idea of setting the variable early and the use of a Singleton is from before they where looked up via the SystemDictionary.
Now we can simplify:

- SystemDictionary should instantiate and not use singleton (we should have one instance of "self" per environment)
- check all uses  #thisContextNode, #selfNode, #superNode. Just create an AST node with the name and let the name analysis later do the lookup and put the instance it finds via SystemDictionary
- Think about Terminology. Traditionally they are called "PseudoVariables", maybe we should change the terminology everywhere

**Comment by privat** [comment]
What it `self` or `thisContext` (or `super`, but this one is weirder)?
As source code elements or AST nodes, the answer is easy, they are occurrences of words in some method definitions.
But as variable, with a scope, the answer is less obvious.

I was surprised when I discovered that reserved variable are singletons, but it kind of make sense as, for instance, the name `self` is visible everywhere and correspond everywhere to the current receiver.

What will be the benefits of having a `self` per environment? How can two `self` differs?

**Comment by MarcusDenker** [comment]
They used to be hard coded in #lookupVar:, thisContext in the methodScope and self/super in an "instance scope" that was used to lookup ivars/slots instead of  #lookupVar: in Behavior and using that as a Scope. 

The lookup we have now feels much better (to me). At first I was not 100% sure about them being part of the global scope, I guess the alternative would be the method scope, maybe because this would allow us to not have singletons.

I think the reason for not having singletons would be that one then could easier have environments that use a re-defined SelfVariable class. Conceptionally it feels odd that a SystemDictionary would be forced to use one shared instance. e.g. if the environment defines SelfVariable, it should have an instance of *that* class as the SelfVariable, not forced one of another SystemDictionary instance.

**Comment by privat** [comment]
From a pure low-level OO design, what are the benefits of having multiple `self`. How the state or the behavior of one instance will be different of the state or behavior of another instance? What will be the implementation of `=`?

`self` can be seen as a pseudo 0th parameter of a method definition, so a method scope might have sense. (so one `self` per method?)
`self` can also be seen as a pseudo *identity* ivar, so introduced in the root of the class hierarchy. (so one `self` per `ProtoObject`?)
`self` can also be seen as a VM way to access the current receiver. (so one `self` per VM? so global and unique, like currently)

Maybe too much philosophy make the design process harder :)

**Comment by MarcusDenker** [comment]
- [x] ReservedVariable: No need for Singleton #13688
- [x] Simplify ReservedVariable: #styleNameIn and remove #nameIsReserved: #13701
- [x] re-think #nameIsReserved:, do we need it? #13701
- [x] SlotErrorsTest>>#testClassSlotWithReservedName, Slot class>>#isPseudovariableName:  #13704
- [x] Compile 'thisContext' (and all other PseudoVariables) as DoitVariable in DoIts #13812
- [x] Think about Terminology. Traditionally they are called "PseudoVariables". And if we allow shadowing, they actually would *not* be reserved, they would just exist due to how we bootrap the environment: #14071
- [x] rename ivar in SystemDictionary #14082

TODO:
- OCASTSemanticAnalyzer>>#shadowing:withVariable: and sender of #isReservedVariable. As these are just variables, we should think about allowing shadowing just like any other Variable (with tools doing the warning, of course)

**Comment by MarcusDenker** [comment]
For the TODO, I will open a new issue later
