### ISSUE TITLE
[Meta] Project view of Calypso improvements

### ISSUE THREAD

**Issue by jecisc** [guillep/pharo-core#15321]
Here is a meta issue for me to remember what can be the improvements to do to the project view

- [ ] Fix bug in refresh of project (when adding, removing or renaming a project, the view is not updated)
- [ ] Speed up projects computation (We should not recreate everything all the time)
- [ ] Check performances (To see if everything slow can get solved with the previous item)
- [ ] FileOut for projects
- [ ] Rename project
- [ ] Project Scope for refactorings and browsing
- [ ] Dependency analyzer for a project
- [x] Do not crash if there is an error in a baseline
- [ ] New Package opens a debugger

**Comment by jecisc** [comment]
I'm closing because Calypso will be redone in Spec so I don't want to lose too much time for my code to be replaced right after
