### ISSUE TITLE
[Cleanup] CompiledBlock instances are created with #newMethod:header: 

### ISSUE THREAD

**Issue by MarcusDenker** [guillep/pharo-core#15625]
**Describe the problem**
CompiledBlock instances are created with #newMethod:header:, which is very confusing.

We should rename it to basicNew:header:

**Comment by MarcusDenker** [comment]
- [x] fix SindarinDebuggerTest>>#testIsAboutToInstantiateClass https://github.com/pharo-spec/ScriptableDebugger/issues/87
- [ ] deprecate #newMethod:header: with rewrite

DONE:
- [x] add #basicNew:header: and use it https://github.com/pharo-project/pharo/pull/15626
- [x] Object>>#clone has code for CompiledCode class #15640
- [x]  move error handling from CompiledMethod to CompiledCode and rename #15651

**Comment by MarcusDenker** [comment]
merged!
