### ISSUE TITLE
unload package Deprecated90 in Pharo10

### ISSUE THREAD

**Issue by MarcusDenker** [guillep/pharo-core#9646]
We should unload Deprecated90

**Comment by MarcusDenker** [comment]
TODOs to fix before we can remove the package:

- [x] Debugger tests where using a deprecated method: https://github.com/pharo-spec/NewTools/pull/267
- [x] TextConverter is still used: https://github.com/pharo-project/pharo/issues/9798

**Comment by MarcusDenker** [comment]
TODO:

- [x] Cleanup-unsent-Deprecated90 #10833
- [x]  [Cleanup Deprecated90] Character>>#leadingChar #10238
- [x] [Cleanup Deprecated90] Character>>#unicodeToMacRoman #10237
